name: Analysis SonarQube

on:
  push:
    branches: ['master']
    paths-ignore:
      - '.husky/README.md'
  pull_request:
    branches: ['master']
    types: [opened, synchronize, reopened]
    paths-ignore:
      - '.husky/README.md'

jobs:
  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
